### PR TITLE
Move "Editors with AutoHotkey Support" to separate page

### PR DESCRIPTION
**Pull request by white-gthb**
"Editors with AutoHotkey Support" was on the page about the Edit command. Removed it there because it is not about the Edit command, but is related. So I created a new page for it and added a link to Related on the Edit page.

* I have changed all references on other pages.
* I have added a help index entry, named "editors".
* I have updated the search index. There is currently an issue with build_search.ahk (not related to my changes), but found a workaround.
* Fixed missing closing html tag in Install.htm.

If this PR is approved, link in UX\ui-editor.ahk should be adjusted too.

### CODE REVIEW

**Comment by Ragnar-F** [comment]
Not a bad idea, but I'll leave the final decision to @Lexikos, since it is a somewhat bigger change.

However, I noticed a few things that are worth changing:
- Move Editors.htm into the misc/ folder. When it comes to third-party software, this folder is a better place for such pages.
- In Edit.htm, change `various editors - see below` to `<a href="../misc/Editors.htm">various editors</a>` or similar.
- Add `<meta name="ahk:equiv-v1" content="lib/Edit.htm#Editors" />` to Edit.htm, directly below `<meta name="description"...`.
- Add "Editors" to data_toc.js, at the same level as and directly before "Debugging Clients".

**Comment by white-gthb** [comment]
> * Move Editors.htm into the misc/ folder. When it comes to third-party software, this folder is a better place for such pages.

That was my first thought too. Then I examined closely where the files are located. It seemed to me it depends on where they are referenced. That's the reason why I placed it in the root, it seemed more in line with other files like AHKL_DBGPClients.htm and FAQ.htm. For now I didn't move Editors.htm to misc/, but I will if you want me to. Please let me know.

> * In Edit.htm, change `various editors - see below` to `<a href="../misc/Editors.htm">various editors</a>` or similar.

Fixed, thanks. But as said, for now I didn't move Editors.htm to misc/.

> * Add `<meta name="ahk:equiv-v1" content="lib/Edit.htm#Editors" />` to Edit.htm, directly below `<meta name="description"...`.

I think you mean Editors.htm.
Done, thanks.

> * Add "Editors" to data_toc.js, at the same level as and directly before "Debugging Clients".

That was my first thought too. Then I realized it wasn't included there before, only at several other places. Most prominently at the starting point of the Help under Quick Reference there is the link "Text editors with AutoHotkey support".
That's the reason I didn't add it. For now I didn't change it. Please let me know if you want me to add it.

**Comment by Ragnar-F** [comment]
> That was my first thought too. Then I examined closely where the files are located. It seemed to me it depends on where they are referenced. That's the reason why I placed it in the root, it seemed more in line with other files like AHKL_DBGPClients.htm and FAQ.htm. For now I didn't move Editors.htm to misc/, but I will if you want me to. Please let me know.

Yes, please do it. AHKL_DBGPClients.htm is a candidate to be renamed anyway. This could be combined with moving it to misc/.

> That was my first thought too. Then I realized it wasn't included there before, only at several other places. Most prominently at the starting point of the Help under Quick Reference there is the link "Text editors with AutoHotkey support".
That's the reason I didn't add it. For now I didn't change it. Please let me know if you want me to add it.

Now that it's a separate page, and because of the usefulness and importance of editors, there's enough reason to add an extra entry for editors in data_toc.js. So please do it.

**Comment by white-gthb** [comment]
Done. Moved AHKL_DBGPClients.htm as well.

For now I have added ahk v1 equiv to AHKL_DBGPClients.htm. If this PR is approved, v1 branch must be adjusted as well. Either by adding ahk v2 equiv or moving AHKL_DBGPClients.htm to misc/ in the v1 branch as well.

**Comment by Ragnar-F** [comment]
I appreciate your efforts, but my thought regarding AHKL_DBGPClients.htm was not meant to be implemented right away. Could you please revert this?

**Comment by white-gthb** [comment]
> I appreciate your efforts, but my thought regarding AHKL_DBGPClients.htm was not meant to be implemented right away. Could you please revert this?

Done.

**Pull request merged**
