### PR TITLE
Content Changes

### PR DESCRIPTION
**Pull request by Ragnar-F**

### CODE REVIEW

**Comment by Lexikos** [comment]
Under Documentation Conventions, there is a paragraph about lists of values in syntax blocks. Is this now obsolete?
https://autohotkey.com/docs/Language.htm#documentation-conventions

**Comment by Ragnar-F** [comment]
No, it's not. AutoTrim, GroupClose, ListView, MouseClick, MouseGetPos, Run, SendMode, SetTimer, SetTitleMatchMode, StringCaseSense, StringGetPos, #MaxThreadsBuffer, #SingleInstance and #UseHook are still left.

Should I also change their parameter names? That wouldn't be much of an effort.

**Comment by Lexikos** [comment]
Either way.

What's with "adopted from v2"?

**Comment by Ragnar-F** [comment]
The parameter name changes have already been applied to the v2 docs (when adding the parameter types).

**Comment by Lexikos** [comment]
I see. I had not updated my local docs.

**Pull request merged**
