### PR TITLE
Use github link instead of forum link

### PR DESCRIPTION
**Pull request by white-gthb**
Use github link instead of forum link for information about setting up Notepad++ for AutoHotkey.
The github page is better, more up-to-date and the forum link is included on this page as well.

### CODE REVIEW

**Comment by Ragnar-F** [comment]
Similarly, there is an easily recognizable link to the GitHub repo in the forum topic. Regarding GitHub vs forum, the forum is always preferred as long as the topic is reasonably up-to-date (to encourage the user to use the forum, since it is the main place for AutoHotkey after all).

@jNizM, which link do you prefer? Maybe you could also update the forum topic.

**Comment by jNizM** [comment]
I try to update the forum post the days. Regarding the link I have no preference.

**Comment by white-gthb** [comment]
Please include a link to the github repository in the OP on the forum as well.

**Comment by jNizM** [comment]
Added the Forum.txt in my Repository ([1198945](https://github.com/jNizM/ahk_notepad-plus-plus/commit/1198945d7ce4776bd975cd1f013e5445ab274329))

**Comment by white-gthb** [comment]
Thanks, was just thinking about that.

**Comment by white-gthb** [comment]
Lol, now I see the title in the forum post is a link to the repository. I didn't notice that before ;)

**Comment by white-gthb** [comment]
@jNizM
I updated Forum.txt. I hope you like it.

**Comment by jNizM** [comment]
Forum post is updated. The rest (docs) is up to you @Ragnar-F .

**Comment by white-gthb** [comment]
Thanks for updating [jNizM](https://github.com/jNizM).
I put a link to github/ahk forum at the top of forum page/github page, so you can easily swap between the two.
This PR has become a non-issue, so I will close it.

**Comment by Ragnar-F** [comment]
Thanks. So there is no need to change the link.

**Pull request closed without merging**
