### PR TITLE
Add ControlID mention in Gui.htm

### PR DESCRIPTION
**Pull request by kyklish**
For better search `ControlID` important stuff in `Gui.html`

### CODE REVIEW

**Comment by Ragnar-F** [comment]
Okay, valid reason in terms of search, but ControlID related to A_GuiControl doesn't make sense. If you can manage to change the sentence slightly so that it makes sense, then I'm inclined to merge that.

**Comment by kyklish** [comment]
Agree, but sorry @Ragnar-F, I'm bad at English. Can you propose proper sentence here, so I add it to PR or make your own PR?

**Comment by Ragnar-F** [comment]
Changed via https://github.com/AutoHotkey/AutoHotkeyDocs/commit/a2fccf87903a410e3db8e7fed4141fa7a21eff9a

**Comment by kyklish** [comment]
@Ragnar-F Thanks :+1:

**Pull request closed without merging**
