### PR TITLE
Update ListView and TreeView

### PR DESCRIPTION
**Pull request by RaptorX**
Reflect alternate syntax so it can be found on the search function

### CODE REVIEW

**Comment by Ragnar-F** [comment]
Could you please do it as shown on the [GUI Control Types](https://www.autohotkey.com/docs/v2/lib/GuiControls.htm) page, i.e. 2 syntax boxes instead of one? And take care that `id="GuiAdd"` is allowed to be present only once.

**Comment by RaptorX** [comment]
Sure, will do.

**Comment by RaptorX** [comment]
> Could you please do it as shown on the [GUI Control Types](https://www.autohotkey.com/docs/v2/lib/GuiControls.htm) page, i.e. 2 syntax boxes instead of one? And take care that `id="GuiAdd"` is allowed to be present only once.

done, please review.

**Comment by Ragnar-F** [comment]
Please remove the line breaks within the pre elements. Some older browsers interpret them as empty lines. Also, both "Or:" must be enclosed by p tags.

**Comment by Ragnar-F** [comment]
Thanks

**Pull request merged**
