### PR TITLE
Update Process.htm

### PR DESCRIPTION
**Pull request by icc2icc**
encapsulated as a function

### CODE REVIEW

**Comment by Ragnar-F** [comment]
I will merge this, but with changes, because the code can be simplified significantly and is therefore better placed in the Close section. Encapsulating as a function is rather unnecessary, because there are already v1 libs that provide commands as functions, and there is v2.

Some notes for your function if you want to continue using it: Compared to the command, the function's PIDOrName is not optional for "Exist" and "CloseAll" is case-sensitive due to `==`.

**Comment by icc2icc** [comment]
Thanks for your fix.
Unfortunately, your code didn't work. It only worked when adding a sleep
function.
 (due to the impact looping too fast,so it caused Windows to respond with
error level 0,even when there was still such a process name)
 When I added* sleep, 20*, it worked on two windows, but when I tried it on
multiple windows, it got stuck somewhere.
VS my code that checks for existence in each loop, which actually consumes
more time and resources, but it's at least reliable.
so the most closes to your code that didnt include the function would be


* Loop{ Process, Close, notepad.exe Process, Exist, * *notepad.exe*
* }Until not ErrorLevel*

Also if you can please explain what you meant with *the function's
PIDOrName is not optional for "Exist"*
Thanks

**Comment by icc2icc** [comment]
Thanks for your fix.
Unfortunately, your code didn't work. It only worked when adding a sleep
function.
 (due to the impact looping too fast,so it caused Windows to respond with
error level 0,even when there was still such a process name)
 When I added "**sleep, 20**", it worked on two windows, but when I tried it on
multiple windows, it got stuck somewhere.
VS my code that checks for existence in each loop, which actually consumes
more time and resources, but it's at least reliable.
so the closest to your code (that didnt include the function) in a working example would be


```
Loop{
  Process, Close, notepad.exe
  Process, Exist, notepad.exe
 }Until not ErrorLevel

```
Also if you can please explain what you meant with 

> the function's
> PIDOrName is not optional for "Exist"

Thanks

**Comment by Ragnar-F** [comment]
You're right. Too bad it's not that easy. With Notepad processes it worked (at least for me), but with other processes it may fail. I've changed the example accordingly. Thanks for testing.

> Also if you can please explain what you meant with

For `Process, Exist`, PIDOrName can be blank or omitted to retrieve the script's own PID. PIDOrName cannot be omitted for your process() function (i.e. `process("Exist")`), as the second parameter is mandatory, but it can at least be blank (an empty string).

**Comment by white-gthb** [comment]
Comment about code formatting:
Shouldn't the opening bracket of the loop block be on a new line, so it is consistent with Example 4 and with the examples you see on the help page of the Loop command?

**Comment by Ragnar-F** [comment]
If it does not interfere with clarity, the OTB style is allowed to be used, but it should follow the usual usage in the docs, as shown e.g. on the Loop page (i.e. the opening brace should be preceded by a space).

**Pull request merged**
